/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sandbox */

#ifndef _Included_Sandbox
#define _Included_Sandbox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sandbox
 * Method:    setLimits
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_Sandbox_setLimits
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     Sandbox
 * Method:    closeLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Sandbox_closeLog
  (JNIEnv *, jclass);

/*
 * Class:     Sandbox
 * Method:    logError
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Sandbox_logError
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
